`include "constant.v"
`include "instr_code.v"



module core_top (
    input  wire        aclk,
    input  wire        aresetn,

    input  wire [ 7:0] intrpt,

    // read requast channel
    output wire [ 3:0] arid,
    output wire [31:0] araddr,
    output wire [ 7:0] arlen,
    output wire [ 2:0] arsize,
    output wire [ 1:0] arburst,
    output wire [ 1:0] arlock,
    output wire [ 3:0] arcache,
    output wire [ 2:0] arprot,
    output wire        arvalid,
    input  wire        arready,
    // read response channel
    input  wire [ 3:0] rid,
    input  wire [31:0] rdata,
    input  wire [ 1:0] rresp,
    input  wire        rlast,
    input  wire        rvalid,
    output wire        rready,
    // write requast channel
    output wire [ 3:0] awid,
    output wire [31:0] awaddr,
    output wire [ 7:0] awlen,
    output wire [ 2:0] awsize,
    output wire [ 1:0] awburst,
    output wire [ 1:0] awlock,
    output wire [ 3:0] awcache,
    output wire [ 2:0] awprot,
    output wire        awvalid,
    input  wire        awready,
    // write data channel
    output wire [ 3:0] wid,
    output wire [31:0] wdata,
    output wire [ 3:0] wstrb,
    output wire        wlast,
    output wire        wvalid,
    input  wire        wready,
    // write response channel
    input  wire [ 3:0] bid,
    input  wire [ 1:0] bresp,
    input  wire        bvalid,
    output wire        bready,
    // trace debug interface
    input  wire        break_point,
    input  wire        infor_flag,
    input  wire [ 4:0] reg_num,
    output wire        ws_valid,
    output wire        rf_rdata,
    output wire [31:0] debug0_wb_pc,
    output wire [ 3:0] debug0_wb_rf_wen,
    output wire [ 4:0] debug0_wb_rf_wnum,
    output wire [31:0] debug0_wb_rf_wdata
);

`ifdef CHIPLAB
mycpu_top u_mycpu_top (
    .aclk             (aclk),
    .aresetn          (aresetn),
`ifdef CHIPLAB
    .intrpt           (intrpt),
`endif
    .arid             (arid),
    .araddr           (araddr),
    .arlen            (arlen),
    .arsize           (arsize),
    .arburst          (arburst),
    .arlock           (arlock),
    .arcache          (arcache),
    .arprot           (arprot),
    .arvalid          (arvalid),
    .arready          (arready),
    .rid              (rid),
    .rdata            (rdata),
    .rresp            (rresp),
    .rlast            (rlast),
    .rvalid           (rvalid),
    .rready           (rready),
    .awid             (awid),
    .awaddr           (awaddr),
    .awlen            (awlen),
    .awsize           (awsize),
    .awburst          (awburst),
    .awlock           (awlock),
    .awcache          (awcache),
    .awprot           (awprot),
    .awvalid          (awvalid),
    .awready          (awready),
    .wid              (wid),
    .wdata            (wdata),
    .wstrb            (wstrb),
    .wlast            (wlast),
    .wvalid           (wvalid),
    .wready           (wready),
    .bid              (bid),
    .bresp            (bresp),
    .bvalid           (bvalid),
    .bready           (bready),
    .debug_wb_pc      (debug0_wb_pc),
    .debug_wb_rf_we   (debug0_wb_rf_wen),
    .debug_wb_rf_wnum (debug0_wb_rf_wnum),
    .debug_wb_rf_wdata(debug0_wb_rf_wdata)
);

/*
`ifdef CHIPLAB
    my_difftest #(
        .TLB_ENTRIES(`TLB_ENTRIES)
    ) my_difftest (
        .clk             (u_mycpu_top.u_mycpu_sram.clk),
        .reset           (u_mycpu_top.u_mycpu_sram.reset),
        .valid           (u_mycpu_top.u_mycpu_sram.W_valid),
        .PC              (u_mycpu_top.u_mycpu_sram.W_PC),
        .instr           (u_mycpu_top.u_mycpu_sram.W_instr),
        .GPR_write_enable(u_mycpu_top.u_mycpu_sram.WB_GPR_write_enable),
        .GPR_write_num   (u_mycpu_top.u_mycpu_sram.WB_GPR_write_num),
        .GPR_write_data  (u_mycpu_top.u_mycpu_sram.WB_GPR_write_data),
        .CSR_read_data   (u_mycpu_top.u_mycpu_sram.WB_CSR_read_data),
        .CSR_counter     (u_mycpu_top.u_mycpu_sram.WB_CSR_counter),
        .CSR_write_enable(u_mycpu_top.u_mycpu_sram.WB_CSR_write_enable),
        .CSR_write_number(u_mycpu_top.u_mycpu_sram.WB_CSR_write_number),
        .TLB_f_index     (u_mycpu_top.u_mycpu_sram.TLB_f_index),
        .TLB_operation   (u_mycpu_top.u_mycpu_sram.WB_TLB_operation),
        .exception       (u_mycpu_top.u_mycpu_sram.exception),
        .ereturn         (u_mycpu_top.u_mycpu_sram.ereturn),
        .ecode           (u_mycpu_top.u_mycpu_sram.csr_file.ecode),
        .MEM_read        (u_mycpu_top.u_mycpu_sram.WB_MEM_read),
        .MEM_write       (u_mycpu_top.u_mycpu_sram.WB_MEM_write),
        .MEM_vaddr       (u_mycpu_top.u_mycpu_sram.W_alu_result),
        .MEM_paddr       (u_mycpu_top.u_mycpu_sram.W_paddr),
        //.llbit           (u_mycpu_top.u_mycpu_sram.WB_llbit),
        .llbit           (),
        .rd_data         (u_mycpu_top.u_mycpu_sram.W_rdkVal),
        .CRMD            (u_mycpu_top.u_mycpu_sram.u_CSRF.CRMD),
        .PRMD            (u_mycpu_top.u_mycpu_sram.u_CSRF.PRMD),
        .EUEN            (),
        .ECFG            (u_mycpu_top.u_mycpu_sram.u_CSRF.ECFG),
        .ESTAT           (u_mycpu_top.u_mycpu_sram.u_CSRF.ESTAT),
        .ERA             (u_mycpu_top.u_mycpu_sram.u_CSRF.ERA),
        .BADV            (u_mycpu_top.u_mycpu_sram.u_CSRF.BADV),
        .EENTRY          (u_mycpu_top.u_mycpu_sram.u_CSRF.EENTRY),
        .TLBIDX          (u_mycpu_top.u_mycpu_sram.u_CSRF.TLBIDX),
        .TLBEHI          (u_mycpu_top.u_mycpu_sram.u_CSRF.TLBEHI),
        .TLBELO0         (u_mycpu_top.u_mycpu_sram.u_CSRF.TLBELO0),
        .TLBELO1         (u_mycpu_top.u_mycpu_sram.u_CSRF.TLBELO1),
        .ASID            (u_mycpu_top.u_mycpu_sram.u_CSRF.ASID),
        .PGDL            (u_mycpu_top.u_mycpu_sram.u_CSRF.PGDL),
        .PGDH            (u_mycpu_top.u_mycpu_sram.u_CSRF.PGDH),
        .SAVE0           (u_mycpu_top.u_mycpu_sram.u_CSRF.SAVE[0]),
        .SAVE1           (u_mycpu_top.u_mycpu_sram.u_CSRF.SAVE[1]),
        .SAVE2           (u_mycpu_top.u_mycpu_sram.u_CSRF.SAVE[2]),
        .SAVE3           (u_mycpu_top.u_mycpu_sram.u_CSRF.SAVE[3]),
        .TID             (u_mycpu_top.u_mycpu_sram.u_CSRF.TID),
        .TCFG            (u_mycpu_top.u_mycpu_sram.u_CSRF.TCFG),
        .TVAL            (u_mycpu_top.u_mycpu_sram.u_CSRF.TVAL),
        .TICLR           (u_mycpu_top.u_mycpu_sram.u_CSRF.TICLR),
        .LLBCTL          (u_mycpu_top.u_mycpu_sram.u_CSRF.LLBCTL),
        .TLBRENTRY       (u_mycpu_top.u_mycpu_sram.u_CSRF.TLBRENTRY),
        .DMW0            (u_mycpu_top.u_mycpu_sram.u_CSRF.DMW[0]),
        .DMW1            (u_mycpu_top.u_mycpu_sram.u_CSRF.DMW[1]),
        .GPR             (u_mycpu_top.u_mycpu_sram.d_GRF.d_grf)
    );
`endif
*/

my_difftest u_my_difftest(
    .clk            (u_mycpu_top.clk),           
    .reset          (u_mycpu_top.reset          ),
    .valid          (u_mycpu_top.W_valid          ),
    .PC             (u_mycpu_top.W_PC             ),
    .instr          (u_mycpu_top.W_instr          ),
    .regWrite       (u_mycpu_top.W_regWrite       ),
    .regWriteAddr   (u_mycpu_top.W_regWriteAddr   ),
    .regWriteData   (u_mycpu_top.W_regWriteData   ),
    .csrReadData    (u_mycpu_top.W_csrReadData    ),
    .counterVal     ({u_mycpu_top.W_highCnt,
                        u_mycpu_top.W_lowCnt}),
    .csrWrite       (u_mycpu_top.W_csrWrite       ),
    .isCsrRead      (u_mycpu_top.d_control.csrrd),
    .isCsrWrite      (u_mycpu_top.d_control.csrwr),
    .isCsrXchg      (u_mycpu_top.d_control.csrxchg),
    .csrWriteAddr   (u_mycpu_top.W_csrWriteAddr   ),
    .TLB_f_index    (u_mycpu_top.W_TLB_f_index    ),
    .TLB_operation  (u_mycpu_top.W_real_tlb_op    ),
    .exception      (u_mycpu_top.exception      ),
    .errorReturn    (u_mycpu_top.errorReturn    ),
    .ecode          (u_mycpu_top.u_CSRF.ecode          ),
    
    .LL_bit         (u_mycpu_top.W_LL_bit),
    .is_SC_W         (u_mycpu_top.W_is_SC_W),
    .is_LL_W         (u_mycpu_top.W_is_LL_W),
    .memWrite       (u_mycpu_top.W_memWrite       ),
    .memReadOrWrite (u_mycpu_top.W_memReadOrWrite ),
    .memSigned      (u_mycpu_top.W_memSigned      ),
    .memDataType    (u_mycpu_top.W_memDataType    ),
    .memPaddr       (u_mycpu_top.W_paddr       ),
    .memVaddr       (u_mycpu_top.W_alu_result       ),
    .rdVal          (u_mycpu_top.W_rdkVal          ),
    .CRMD           (u_mycpu_top.u_CSRF.CRMD           ),
    .PRMD           (u_mycpu_top.u_CSRF.PRMD           ),
    //.EUEN           (u_mycpu_top.u_mycpu_sram.u_CSRF.EUEN           ),
    .EUEN           (),
    .ECFG           (u_mycpu_top.u_CSRF.ECFG           ),
    .ESTAT          (u_mycpu_top.u_CSRF.ESTAT          ),
    .ERA            (u_mycpu_top.u_CSRF.ERA            ),
    .BADV           (u_mycpu_top.u_CSRF.BADV           ),
    .EENTRY         (u_mycpu_top.u_CSRF.EENTRY         ),
    .TLBIDX         (u_mycpu_top.u_CSRF.TLBIDX         ),
    .TLBEHI         (u_mycpu_top.u_CSRF.TLBEHI         ),
    .TLBELO0        (u_mycpu_top.u_CSRF.TLBELO0        ),
    .TLBELO1        (u_mycpu_top.u_CSRF.TLBELO1        ),
    .ASID           (u_mycpu_top.u_CSRF.ASID           ),
    .PGDL           (u_mycpu_top.u_CSRF.PGDL           ),
    .PGDH           (u_mycpu_top.u_CSRF.PGDH           ),
    .SAVE0          (u_mycpu_top.u_CSRF.SAVE[0]          ),
    .SAVE1          (u_mycpu_top.u_CSRF.SAVE[1]          ),
    .SAVE2          (u_mycpu_top.u_CSRF.SAVE[2]          ),
    .SAVE3          (u_mycpu_top.u_CSRF.SAVE[3]          ),
    .TID            (u_mycpu_top.u_CSRF.TID            ),
    .TCFG           (u_mycpu_top.u_CSRF.TCFG           ),
    .TVAL           (u_mycpu_top.u_CSRF.TVAL           ),
    .TICLR          (u_mycpu_top.u_CSRF.TICLR          ),
    .LLBCTL         (u_mycpu_top.u_CSRF.LLBCTL         ),
    .TLBRENTRY      (u_mycpu_top.u_CSRF.TLBRENTRY      ),
    .DMW0           (u_mycpu_top.u_CSRF.DMW[0]           ),
    .DMW1           (u_mycpu_top.u_CSRF.DMW[1]           ),
    .GPR            (u_mycpu_top.d_GRF.d_grf            )
);

`endif

endmodule
